### ISSUE TITLE
User Story #9: Implement the front end for the button that will be used to endorse the post

### ISSUE THREAD

**Issue by evelynzhengg** [CMU-313/nodebb-f24-aawaa#9]
Button Design
Estimated Effort: 5-7 hours
Dependencies: None
Acceptance criteria: Professors intuitively understand what the purpose of the button is and how to use it.

**Comment by ogometz** [comment]
This issue was removed from sprint 2 after our team had a re-scoping meeting following failures in sprint 1 planning. After sprint 1, our team decided to split up work by feature. Along with this, our team decided to come up with a few new user stories to implement so it can be managed by one person

**Comment by Nita242004** [comment]
This issue is redundant.
